---
- name: Get start time
  # shell: "date"
  shell: 'date +"%Y-%m-%d_%H-%M"'
  delegate_to: localhost
  run_once: true
  register: tstamp

- name: Set a folder name for outputs
  ansible.builtin.set_fact:
    folder_name: "./outputs/{{ tstamp.stdout }}"
  delegate_to: localhost
  run_once: true

- name: Create a folder for command outputs
  ansible.builtin.file:
    path: "{{ folder_name }}/command_outputs"
    state: directory
    # mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Create a folder for python parser outputs
  ansible.builtin.file:
    path: "{{ folder_name }}/script_outputs/{{ item }}"
    state: directory
    # mode: '0755'
  delegate_to: localhost
  run_once: true
  loop:
    - excel
    - csv
    - json

### Collecting and Parsing show interface status outputs

- name: Get show interface status command outputs in XML format
  cisco.nxos.nxos_command:
    commands:
      - show interface status | xml | exclude ]]>]]>
  register: outputs_int_status_xml

- name: Copy show interface status outputs to a file
  ansible.builtin.lineinfile:
    path: "{{ folder_name }}/command_outputs/{{ inventory_hostname }}_show_interface_status.xml"
    line: |
      {{ outputs_int_status_xml.stdout | join('\n') }}
    state: present
    create: true

- name: Convert XML outputs to CSV
  ansible.builtin.command:
    cmd: "python3 xml2csv_interface_output.py"
    executable: /Users/timkinv0815/Documents/venv3106/bin/python3
    chdir: ./roles/get_interface_status/library
    stdin: |
      {{ tstamp.stdout }},{{ inventory_hostname }}
  delegate_to: localhost
  # register: output_xml2csv

### Collecting and Parsing CDP outputs

- name: Get show cdp enty command outputs
  cisco.nxos.nxos_command:
    commands:
      - show cdp entry all
  register: outputs_cdp_entries

- name: Copy show cdp entry all outputs to a file
  ansible.builtin.lineinfile:
    path: "{{ folder_name }}/command_outputs/{{ inventory_hostname }}_show_cdp_entry.txt"
    line: |
      {{ outputs_cdp_entries.stdout | join('\n') }}
    state: present
    create: true

- name: Parsing CDP outputs
  ansible.builtin.command:
    cmd: "python3 cdp_parser.py"
    executable: /Users/timkinv0815/Documents/venv3106/bin/python3
    chdir: ./roles/get_interface_status/library
    stdin: |
      {{ tstamp.stdout }},{{ inventory_hostname }}
  delegate_to: localhost
  # register: output_cdp_parser

### Collecting and Parsing LLDP outputs

- name: Get show lldp enty command outputs
  cisco.nxos.nxos_command:
    commands:
      - show lldp entry
  register: outputs_lldp_entries

- name: Copy show lldp entry outputs to a file
  ansible.builtin.lineinfile:
    path: "{{ folder_name }}/command_outputs/{{ inventory_hostname }}_show_lldp_entry.txt"
    line: |
      {{ outputs_lldp_entries.stdout | join('\n') }}
    state: present
    create: true

- name: Parsing lldp outputs
  ansible.builtin.command:
    cmd: "python3 lldp_parser.py"
    executable: /Users/timkinv0815/Documents/venv3106/bin/python3
    chdir: ./roles/get_interface_status/library
    stdin: |
      {{ tstamp.stdout }},{{ inventory_hostname }}
  delegate_to: localhost
  # register: output_lldp_parser
...